repos:
  - hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-builtin-literals
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
  - hooks:
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
  - hooks:
      - id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.13.2
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.8.0
  - hooks:
      - additional_dependencies:
          - flake8-absolute-import==1.0.0.2
          - flake8-bandit==4.1.1
          - flake8-bugbear==24.8.19
          - flake8-builtins==2.5.0
          - flake8-comprehensions==3.15.0
          - flake8-isort==6.1.1
          - flake8-plugin-utils==1.3.3
          - flake8-print==5.0.0
          - flake8-pyproject==1.2.3
          - flake8-return==1.2.0
          - flake8-use-pathlib==0.3.0
          - pep8-naming==0.14.1
          - setuptools==74.1.1
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 7.1.1
